language: node_js
sudo: false
dist: trusty
node_js:
  - "7"

addons:
    chrome: stable

env:
  global:
    - workingDir=$(pwd)    
  matrix:
    - MODE=unit TEST=karma
    - MODE=e2e_cits TEST=smoke
    - MODE=e2e_cits TEST=layout

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g @angular/cli@latest
      # source the env.sh script to get exported variables
    - source ./scripts/ci/env.sh print
    - curl -sL https://raw.githubusercontent.com/x0156/cits-travis-seed/x0156/install.sh | bash
    - . ./sourcefile

install:
    - npm install -g http-server
    - npm install

before_script:  
  - "echo 'echo $*;exit 1;' > fail;chmod u+x fail;"
  - chmod -R +x ./scripts/ci
 
script:
  - ./scripts/ci/travis-script.sh

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
        branch: master

cache:
    directories:
        - $HOME/.npm